import AppKit
import Combine

/// Polls NSPasteboard.general for changes (there is no native change notification API)
/// and turns new content into ClipboardItem history entries.
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    var maxItems = 300

    private let store: ClipboardStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Types apps use to mark content that clipboard managers should not store
    /// (password managers, etc.) — see nspasteboard.org.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
        self.items = store.load()
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after ClipShelf itself writes to the pasteboard (copy/paste-back from
    /// history). Without this, the next poll sees the changeCount bump from our own write
    /// and re-captures it as a "new" copy — for images this even mints a fresh cache file
    /// each time (different filename → dedup doesn't catch it), so clicking the same
    /// image repeatedly spawned duplicate "Bild" rows sourced from ClipShelf itself.
    func syncAfterOwnWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    private func checkPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard let newItem = captureCurrentPasteboard() else { return }
        insert(newItem)
    }

    private func insert(_ newItem: ClipboardItem) {
        if let existingIndex = items.firstIndex(where: { $0.hasSameContent(as: newItem) }) {
            var moved = items.remove(at: existingIndex)
            moved.date = newItem.date
            items.insert(moved, at: 0)
        } else {
            items.insert(newItem, at: 0)
        }

        if items.count > maxItems {
            let pinnedCount = items.filter { $0.pinned }.count
            let unpinnedBudget = max(0, maxItems - pinnedCount)
            var kept: [ClipboardItem] = []
            var removed: [ClipboardItem] = []
            var unpinnedKept = 0
            for item in items {
                if item.pinned {
                    kept.append(item)
                } else if unpinnedKept < unpinnedBudget {
                    kept.append(item)
                    unpinnedKept += 1
                } else {
                    removed.append(item)
                }
            }
            items = kept
            for item in removed {
                store.deleteImageIfNeeded(item, keepAmong: items)
            }
        }

        store.save(items)
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        store.deleteImageIfNeeded(item, keepAmong: items)
        store.save(items)
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        store.save(items)
    }

    func clearAll(keepPinned: Bool = true) {
        let toRemove = keepPinned ? items.filter { !$0.pinned } : items
        items = keepPinned ? items.filter { $0.pinned } : []
        for removed in toRemove {
            store.deleteImageIfNeeded(removed, keepAmong: items)
        }
        store.save(items)
    }

    // MARK: - Capture

    private func captureCurrentPasteboard() -> ClipboardItem? {
        guard let types = pasteboard.types, !types.isEmpty else { return nil }
        if types.contains(where: { Self.excludedTypes.contains($0.rawValue) }) { return nil }

        let source = frontmostAppInfo()

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return ClipboardItem(
                kind: .fileURLs,
                fileURLs: urls,
                sourceAppName: source.name,
                sourceAppBundleID: source.bundleID
            )
        }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let image = NSImage(data: data) {
            guard let fileName = store.imageCache.save(image) else { return nil }
            return ClipboardItem(
                kind: .image,
                imageFileName: fileName,
                sourceAppName: source.name,
                sourceAppBundleID: source.bundleID
            )
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipboardItem(
                kind: .text,
                text: text,
                sourceAppName: source.name,
                sourceAppBundleID: source.bundleID
            )
        }

        return nil
    }

    private func frontmostAppInfo() -> (name: String?, bundleID: String?) {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.localizedName, app?.bundleIdentifier)
    }
}
